### ISSUE TITLE
New branch for express-based server

### ISSUE THREAD

**Issue by aurieh** [AdenFlorian/random.dog#1]
I wrote an implementation of this webserver using express, adding a few more features, and improving speed. I would not want to push this straight to master, so `express` branch would be nice.

https://github.com/aurieh/random.dog/tree/express

**Comment by adenflorian** [comment]
Sorry for late reply, must've missed the email, I have create an express branch :)

**Comment by aurieh** [comment]
Awesome, I will create a PR asap!
