### ISSUE TITLE
inclusive filter support

### ISSUE THREAD

**Issue by sanan-fataliyev** [AdenFlorian/random.dog#16]
Most of time we need to specify which extensions we want to get.
I think the following filtering would be more intuitive:

`/woof?filter=jpg,jpeg` - return only dogs with `jpg` or `jpeg` ext.
`/woof?exclude=mp4,webm` -  return dogs that don't have `mp4` or `webm` ext.

but if backward compatibility is important,  one solution is to keep current filter logic the same and add `include` query parameter. E.g:

`/woof?filter=mp4,webm` -  return dogs that don't have `mp4 or webm` ext.
`/woof?include=jpg,jpeg` - return only dogs with `jpg` or `jpeg` ext.

priorities: if `include` specified, ignore `filter`

**Comment by adenflorian** [comment]
update is live! there's now an `include` param that just does the opposite of filter.
