### ISSUE TITLE
401 code

### ISSUE THREAD

**Issue by rolfilho** [AdenFlorian/random.dog#4]
Hello Aden,

I'm a newbie who cloned your project for learning purposes. I'm running your app on my Cloud 9 development environment; the upload page works fine, but I'm not able to reach the root route (/) or the review route due to a 401 error.

Likely this has something to do with the secret.json file which I created with something random. I'm not sure how to comply with the checkhash function, not sure how to input a 'password'.

Please let me know if you could help.

PS: I also tried running it locally on my computer, without success.

Tks!

**Comment by adenflorian** [comment]
I'll write something up this weekend! Feel free to remind me if I forget.

**Comment by rolfilho** [comment]
Thanks, Aden!

**Comment by adenflorian** [comment]
@rolfilho 
- The root route `/` shouldn't require any password, so I', not sure why you get a 401 there ☹️ 
- `/review` requires a query param of `bone` with a correct value
  - The value should be some text that, when hashed with bcrypt, matches the hash stored in a file named `secret.json` located in the project root folder
  - The json in `secret.json` should be like this:
    -  `{"secret": "<put hash here>"}`
  -  I think I used [bcrypt-cli](https://www.npmjs.com/package/bcrypt-cli) to hash my password
  - Example URL:
    - `random.dog/review?bone=password`

I did the simplest thing I could think of from an implementation and user perspective.
From what I've read, worst case with putting a secret in query params when it's https, is that it gets stored as plain text in server logs, so as long as I never give anyone else access to my server it should be fine.
I'll add this to the readme.

If this solves your issue then please close this issue, thanks!

**Comment by rolfilho** [comment]
Thanks! It worked :)
