### ISSUE TITLE
Add an api endpoint to get a list of all the dog image paths

### ISSUE THREAD

**Issue by MoralCode** [AdenFlorian/random.dog#5]
I was thinking something like either

http://random.dog/list.json that displays either something like:

    {"list" : ["url1", "url2", "url3", ".etc"]}

or http://random.dog/list that displays just a straight array of values like:

    ["url1", "url2", "url3", ".etc"]

I am currently looking into itegrating your API into a web app and thought this would be a helpful feature to potentially reduce the number of calls to your API.

Thank you so much for this API. Please keep it around!

**Comment by adenflorian** [comment]
I'll look into this over the weekend 😄

**Comment by adenflorian** [comment]
@DeveloperACE It's live!
`GET /doggos`
```json
[
  "00186969-c51d-462b-948b-30a7e1735908.jpg",
  "00b417af-0b5f-42d7-9ad0-6aab6c3db491.jpg"
]
```
