### ISSUE TITLE
A way to filter out file types

### ISSUE THREAD

**Issue by velddev** [AdenFlorian/random.dog#9]
Hey, I'd love a way to filter out filetypes like ".mp4" as they do not run on services I'd like to use this on. My proposal for this would be random.dog/woof?filter="mp4,png".

**Comment by adenflorian** [comment]
Done!

**Comment by JonaCeja54** [comment]
Could you document this feature more? I'd love to use it on my discord bot to not show .mp4 dogs

**Comment by adenflorian** [comment]
@mokingguy Just added a little bit of info on the readme.
